// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module filter_hls_filter_hls_Pipeline_LOAD (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        line_8_address0,
        line_8_ce0,
        line_8_we0,
        line_8_d0,
        line_7_address0,
        line_7_ce0,
        line_7_we0,
        line_7_d0,
        line_6_address0,
        line_6_ce0,
        line_6_we0,
        line_6_d0,
        line_5_address0,
        line_5_ce0,
        line_5_we0,
        line_5_d0,
        line_4_address0,
        line_4_ce0,
        line_4_we0,
        line_4_d0,
        line_3_address0,
        line_3_ce0,
        line_3_we0,
        line_3_d0,
        line_2_address0,
        line_2_ce0,
        line_2_we0,
        line_2_d0,
        line_1_address0,
        line_1_ce0,
        line_1_we0,
        line_1_d0,
        line_r_address0,
        line_r_ce0,
        line_r_we0,
        line_r_d0,
        row_buf_address0,
        row_buf_ce0,
        row_buf_q0,
        urem_ln92
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] line_8_address0;
output   line_8_ce0;
output   line_8_we0;
output  [7:0] line_8_d0;
output  [8:0] line_7_address0;
output   line_7_ce0;
output   line_7_we0;
output  [7:0] line_7_d0;
output  [8:0] line_6_address0;
output   line_6_ce0;
output   line_6_we0;
output  [7:0] line_6_d0;
output  [8:0] line_5_address0;
output   line_5_ce0;
output   line_5_we0;
output  [7:0] line_5_d0;
output  [8:0] line_4_address0;
output   line_4_ce0;
output   line_4_we0;
output  [7:0] line_4_d0;
output  [8:0] line_3_address0;
output   line_3_ce0;
output   line_3_we0;
output  [7:0] line_3_d0;
output  [8:0] line_2_address0;
output   line_2_ce0;
output   line_2_we0;
output  [7:0] line_2_d0;
output  [8:0] line_1_address0;
output   line_1_ce0;
output   line_1_we0;
output  [7:0] line_1_d0;
output  [8:0] line_r_address0;
output   line_r_ce0;
output   line_r_we0;
output  [7:0] line_r_d0;
output  [10:0] row_buf_address0;
output   row_buf_ce0;
input  [31:0] row_buf_q0;
input  [1:0] urem_ln92;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln96_fu_259_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] urem_ln92_read_reg_447;
wire   [1:0] trunc_ln96_fu_276_p1;
reg   [1:0] trunc_ln96_reg_455;
reg   [1:0] trunc_ln96_reg_455_pp0_iter1_reg;
reg   [1:0] trunc_ln96_reg_455_pp0_iter2_reg;
reg   [1:0] trunc_ln96_reg_455_pp0_iter3_reg;
reg   [1:0] trunc_ln96_reg_455_pp0_iter4_reg;
wire   [7:0] trunc_ln98_fu_310_p1;
reg   [7:0] trunc_ln98_reg_464;
reg   [7:0] trunc_ln98_reg_464_pp0_iter2_reg;
reg   [7:0] trunc_ln99_1_reg_469;
wire   [14:0] mul_ln99_fu_344_p2;
wire   [63:0] zext_ln96_fu_271_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln96_1_fu_372_p1;
reg   [10:0] phi_urem20_fu_90;
wire   [10:0] select_ln96_fu_292_p3;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_phi_urem20_load;
reg   [21:0] phi_mul18_fu_94;
wire   [21:0] add_ln96_1_fu_356_p2;
reg   [10:0] x_fu_98;
wire   [10:0] add_ln96_fu_265_p2;
reg   [10:0] ap_sig_allocacmp_x_2;
reg    row_buf_ce0_local;
reg    line_4_we0_local;
reg    line_4_ce0_local;
reg    line_3_we0_local;
reg    line_3_ce0_local;
reg    line_5_we0_local;
reg    line_5_ce0_local;
reg    line_1_we0_local;
reg    line_1_ce0_local;
reg    line_r_we0_local;
reg    line_r_ce0_local;
reg    line_2_we0_local;
reg    line_2_ce0_local;
reg    line_7_we0_local;
reg    line_7_ce0_local;
reg    line_6_we0_local;
reg    line_6_ce0_local;
reg    line_8_we0_local;
reg    line_8_ce0_local;
wire   [0:0] icmp_ln96_1_fu_286_p2;
wire   [10:0] add_ln96_2_fu_280_p2;
wire   [7:0] trunc_ln99_2_fu_324_p4;
wire   [7:0] mul_ln99_fu_344_p0;
wire   [7:0] mul_ln99_fu_344_p1;
wire   [14:0] grp_fu_408_p3;
wire   [8:0] tmp_fu_362_p4;
wire   [15:0] grp_fu_417_p3;
wire   [7:0] grp_fu_408_p0;
wire   [4:0] grp_fu_408_p1;
wire   [7:0] grp_fu_417_p0;
wire   [7:0] grp_fu_417_p1;
wire   [14:0] grp_fu_417_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [12:0] grp_fu_408_p00;
wire   [15:0] grp_fu_417_p00;
wire   [15:0] grp_fu_417_p20;
wire   [14:0] mul_ln99_fu_344_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 phi_urem20_fu_90 = 11'd0;
#0 phi_mul18_fu_94 = 22'd0;
#0 x_fu_98 = 11'd0;
#0 ap_done_reg = 1'b0;
end

filter_hls_mul_8ns_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8ns_8ns_15_1_1_U33(
    .din0(mul_ln99_fu_344_p0),
    .din1(mul_ln99_fu_344_p1),
    .dout(mul_ln99_fu_344_p2)
);

filter_hls_mac_muladd_8ns_5ns_15ns_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_5ns_15ns_15_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_408_p0),
    .din1(grp_fu_408_p1),
    .din2(mul_ln99_fu_344_p2),
    .ce(1'b1),
    .dout(grp_fu_408_p3)
);

filter_hls_mac_muladd_8ns_8ns_15ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8ns_15ns_16_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_417_p0),
    .din1(grp_fu_417_p1),
    .din2(grp_fu_417_p2),
    .ce(1'b1),
    .dout(grp_fu_417_p3)
);

filter_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            phi_mul18_fu_94 <= 22'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            phi_mul18_fu_94 <= add_ln96_1_fu_356_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_259_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            phi_urem20_fu_90 <= select_ln96_fu_292_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            phi_urem20_fu_90 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln96_fu_259_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_98 <= add_ln96_fu_265_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_98 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln96_reg_455 <= trunc_ln96_fu_276_p1;
        trunc_ln96_reg_455_pp0_iter1_reg <= trunc_ln96_reg_455;
        trunc_ln98_reg_464 <= trunc_ln98_fu_310_p1;
        trunc_ln99_1_reg_469 <= {{row_buf_q0[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        trunc_ln96_reg_455_pp0_iter2_reg <= trunc_ln96_reg_455_pp0_iter1_reg;
        trunc_ln96_reg_455_pp0_iter3_reg <= trunc_ln96_reg_455_pp0_iter2_reg;
        trunc_ln96_reg_455_pp0_iter4_reg <= trunc_ln96_reg_455_pp0_iter3_reg;
        trunc_ln98_reg_464_pp0_iter2_reg <= trunc_ln98_reg_464;
    end
end

always @ (*) begin
    if (((icmp_ln96_fu_259_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_phi_urem20_load = 11'd0;
    end else begin
        ap_sig_allocacmp_phi_urem20_load = phi_urem20_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_2 = 11'd0;
    end else begin
        ap_sig_allocacmp_x_2 = x_fu_98;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_1_ce0_local = 1'b1;
    end else begin
        line_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd1) & (urem_ln92_read_reg_447 == 2'd0))) begin
        line_1_we0_local = 1'b1;
    end else begin
        line_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_2_ce0_local = 1'b1;
    end else begin
        line_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd0) & ~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (urem_ln92_read_reg_447 == 2'd0))) begin
        line_2_we0_local = 1'b1;
    end else begin
        line_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_3_ce0_local = 1'b1;
    end else begin
        line_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd0) & (urem_ln92_read_reg_447 == 2'd1))) begin
        line_3_we0_local = 1'b1;
    end else begin
        line_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_4_ce0_local = 1'b1;
    end else begin
        line_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd1) & (urem_ln92_read_reg_447 == 2'd1))) begin
        line_4_we0_local = 1'b1;
    end else begin
        line_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_5_ce0_local = 1'b1;
    end else begin
        line_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd0) & ~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (urem_ln92_read_reg_447 == 2'd1))) begin
        line_5_we0_local = 1'b1;
    end else begin
        line_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_6_ce0_local = 1'b1;
    end else begin
        line_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(urem_ln92_read_reg_447 == 2'd0) & ~(urem_ln92_read_reg_447 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd0))) begin
        line_6_we0_local = 1'b1;
    end else begin
        line_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_7_ce0_local = 1'b1;
    end else begin
        line_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(urem_ln92_read_reg_447 == 2'd0) & ~(urem_ln92_read_reg_447 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd1))) begin
        line_7_we0_local = 1'b1;
    end else begin
        line_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_8_ce0_local = 1'b1;
    end else begin
        line_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(urem_ln92_read_reg_447 == 2'd0) & ~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd0) & ~(trunc_ln96_reg_455_pp0_iter4_reg == 2'd1) & ~(urem_ln92_read_reg_447 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_8_we0_local = 1'b1;
    end else begin
        line_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        line_r_ce0_local = 1'b1;
    end else begin
        line_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln96_reg_455_pp0_iter4_reg == 2'd0) & (urem_ln92_read_reg_447 == 2'd0))) begin
        line_r_we0_local = 1'b1;
    end else begin
        line_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_buf_ce0_local = 1'b1;
    end else begin
        row_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln96_1_fu_356_p2 = (phi_mul18_fu_94 + 22'd2731);

assign add_ln96_2_fu_280_p2 = (ap_sig_allocacmp_phi_urem20_load + 11'd1);

assign add_ln96_fu_265_p2 = (ap_sig_allocacmp_x_2 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_408_p0 = grp_fu_408_p00;

assign grp_fu_408_p00 = trunc_ln99_2_fu_324_p4;

assign grp_fu_408_p1 = 13'd29;

assign grp_fu_417_p0 = grp_fu_417_p00;

assign grp_fu_417_p00 = trunc_ln99_1_reg_469;

assign grp_fu_417_p1 = 16'd150;

assign grp_fu_417_p2 = grp_fu_417_p20;

assign grp_fu_417_p20 = grp_fu_408_p3;

assign icmp_ln96_1_fu_286_p2 = ((ap_sig_allocacmp_phi_urem20_load == 11'd2) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_259_p2 = ((ap_sig_allocacmp_x_2 == 11'd1280) ? 1'b1 : 1'b0);

assign line_1_address0 = zext_ln96_1_fu_372_p1;

assign line_1_ce0 = line_1_ce0_local;

assign line_1_d0 = {{grp_fu_417_p3[15:8]}};

assign line_1_we0 = line_1_we0_local;

assign line_2_address0 = zext_ln96_1_fu_372_p1;

assign line_2_ce0 = line_2_ce0_local;

assign line_2_d0 = {{grp_fu_417_p3[15:8]}};

assign line_2_we0 = line_2_we0_local;

assign line_3_address0 = zext_ln96_1_fu_372_p1;

assign line_3_ce0 = line_3_ce0_local;

assign line_3_d0 = {{grp_fu_417_p3[15:8]}};

assign line_3_we0 = line_3_we0_local;

assign line_4_address0 = zext_ln96_1_fu_372_p1;

assign line_4_ce0 = line_4_ce0_local;

assign line_4_d0 = {{grp_fu_417_p3[15:8]}};

assign line_4_we0 = line_4_we0_local;

assign line_5_address0 = zext_ln96_1_fu_372_p1;

assign line_5_ce0 = line_5_ce0_local;

assign line_5_d0 = {{grp_fu_417_p3[15:8]}};

assign line_5_we0 = line_5_we0_local;

assign line_6_address0 = zext_ln96_1_fu_372_p1;

assign line_6_ce0 = line_6_ce0_local;

assign line_6_d0 = {{grp_fu_417_p3[15:8]}};

assign line_6_we0 = line_6_we0_local;

assign line_7_address0 = zext_ln96_1_fu_372_p1;

assign line_7_ce0 = line_7_ce0_local;

assign line_7_d0 = {{grp_fu_417_p3[15:8]}};

assign line_7_we0 = line_7_we0_local;

assign line_8_address0 = zext_ln96_1_fu_372_p1;

assign line_8_ce0 = line_8_ce0_local;

assign line_8_d0 = {{grp_fu_417_p3[15:8]}};

assign line_8_we0 = line_8_we0_local;

assign line_r_address0 = zext_ln96_1_fu_372_p1;

assign line_r_ce0 = line_r_ce0_local;

assign line_r_d0 = {{grp_fu_417_p3[15:8]}};

assign line_r_we0 = line_r_we0_local;

assign mul_ln99_fu_344_p0 = mul_ln99_fu_344_p00;

assign mul_ln99_fu_344_p00 = trunc_ln98_reg_464_pp0_iter2_reg;

assign mul_ln99_fu_344_p1 = 15'd76;

assign row_buf_address0 = zext_ln96_fu_271_p1;

assign row_buf_ce0 = row_buf_ce0_local;

assign select_ln96_fu_292_p3 = ((icmp_ln96_1_fu_286_p2[0:0] == 1'b1) ? 11'd0 : add_ln96_2_fu_280_p2);

assign tmp_fu_362_p4 = {{phi_mul18_fu_94[21:13]}};

assign trunc_ln96_fu_276_p1 = ap_sig_allocacmp_phi_urem20_load[1:0];

assign trunc_ln98_fu_310_p1 = row_buf_q0[7:0];

assign trunc_ln99_2_fu_324_p4 = {{row_buf_q0[23:16]}};

assign urem_ln92_read_reg_447 = urem_ln92;

assign zext_ln96_1_fu_372_p1 = tmp_fu_362_p4;

assign zext_ln96_fu_271_p1 = ap_sig_allocacmp_x_2;

endmodule //filter_hls_filter_hls_Pipeline_LOAD
