// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module ped_detect_hls_ped_detect_hls_Pipeline_BLK_Y_BLK_X_VITIS_LOOP_101_4_VITIS_LOOP_102_5_VITIS_Lbkb (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 12;
parameter AddressRange = 4096;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./ped_detect_hls_ped_detect_hls_Pipeline_BLK_Y_BLK_X_VITIS_LOOP_101_4_VITIS_LOOP_102_5_VITIS_Lbkb.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

