// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ped_detect_hls_ped_detect_hls_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hist_address0,
        hist_ce0,
        hist_we0,
        hist_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] hist_address0;
output   hist_ce0;
output   hist_we0;
output  [31:0] hist_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_120_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln58_4_fu_286_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] b_fu_58;
wire   [3:0] add_ln57_fu_291_p2;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [5:0] cx_fu_62;
wire   [5:0] select_ln56_fu_210_p3;
reg   [9:0] indvar_flatten_fu_66;
wire   [9:0] select_ln56_1_fu_303_p3;
reg   [4:0] cy_fu_70;
wire   [4:0] select_ln55_1_fu_182_p3;
reg   [13:0] indvar_flatten22_fu_74;
wire   [13:0] add_ln55_1_fu_126_p2;
reg    hist_we0_local;
reg    hist_ce0_local;
wire   [0:0] icmp_ln56_fu_150_p2;
wire   [0:0] icmp_ln57_fu_170_p2;
wire   [0:0] xor_ln55_fu_164_p2;
wire   [4:0] add_ln55_fu_144_p2;
wire   [5:0] select_ln55_fu_156_p3;
wire   [0:0] and_ln55_fu_176_p2;
wire   [0:0] empty_fu_196_p2;
wire   [5:0] add_ln56_fu_190_p2;
wire   [9:0] tmp_fu_218_p3;
wire   [7:0] tmp_1_fu_230_p3;
wire   [10:0] zext_ln58_fu_226_p1;
wire   [10:0] zext_ln58_1_fu_238_p1;
wire   [10:0] add_ln58_2_fu_242_p2;
wire   [10:0] zext_ln58_2_fu_248_p1;
wire   [10:0] add_ln58_fu_252_p2;
wire   [13:0] tmp_2_fu_262_p3;
wire   [13:0] zext_ln57_fu_258_p1;
wire   [3:0] b_mid2_fu_202_p3;
wire   [13:0] add_ln57_1_fu_270_p2;
wire   [13:0] zext_ln58_3_fu_276_p1;
wire   [13:0] add_ln58_1_fu_280_p2;
wire   [9:0] add_ln56_1_fu_297_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 b_fu_58 = 4'd0;
#0 cx_fu_62 = 6'd0;
#0 indvar_flatten_fu_66 = 10'd0;
#0 cy_fu_70 = 5'd0;
#0 indvar_flatten22_fu_74 = 14'd0;
#0 ap_done_reg = 1'b0;
end

ped_detect_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_fu_58 <= 4'd0;
        end else if (((icmp_ln55_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            b_fu_58 <= add_ln57_fu_291_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            cx_fu_62 <= 6'd0;
        end else if (((icmp_ln55_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            cx_fu_62 <= select_ln56_fu_210_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            cy_fu_70 <= 5'd0;
        end else if (((icmp_ln55_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            cy_fu_70 <= select_ln55_1_fu_182_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten22_fu_74 <= 14'd0;
        end else if (((icmp_ln55_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten22_fu_74 <= add_ln55_1_fu_126_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_66 <= 10'd0;
        end else if (((icmp_ln55_fu_120_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_66 <= select_ln56_1_fu_303_p3;
        end
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_120_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_ce0_local = 1'b1;
    end else begin
        hist_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_120_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hist_we0_local = 1'b1;
    end else begin
        hist_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_1_fu_126_p2 = (indvar_flatten22_fu_74 + 14'd1);

assign add_ln55_fu_144_p2 = (cy_fu_70 + 5'd1);

assign add_ln56_1_fu_297_p2 = (indvar_flatten_fu_66 + 10'd1);

assign add_ln56_fu_190_p2 = (select_ln55_fu_156_p3 + 6'd1);

assign add_ln57_1_fu_270_p2 = (tmp_2_fu_262_p3 + zext_ln57_fu_258_p1);

assign add_ln57_fu_291_p2 = (b_mid2_fu_202_p3 + 4'd1);

assign add_ln58_1_fu_280_p2 = (add_ln57_1_fu_270_p2 + zext_ln58_3_fu_276_p1);

assign add_ln58_2_fu_242_p2 = (zext_ln58_fu_226_p1 + zext_ln58_1_fu_238_p1);

assign add_ln58_fu_252_p2 = (add_ln58_2_fu_242_p2 + zext_ln58_2_fu_248_p1);

assign and_ln55_fu_176_p2 = (xor_ln55_fu_164_p2 & icmp_ln57_fu_170_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign b_mid2_fu_202_p3 = ((empty_fu_196_p2[0:0] == 1'b1) ? 4'd0 : b_fu_58);

assign empty_fu_196_p2 = (icmp_ln56_fu_150_p2 | and_ln55_fu_176_p2);

assign hist_address0 = zext_ln58_4_fu_286_p1;

assign hist_ce0 = hist_ce0_local;

assign hist_d0 = 32'd0;

assign hist_we0 = hist_we0_local;

assign icmp_ln55_fu_120_p2 = ((indvar_flatten22_fu_74 == 14'd10800) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_150_p2 = ((indvar_flatten_fu_66 == 10'd360) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_170_p2 = ((b_fu_58 == 4'd9) ? 1'b1 : 1'b0);

assign select_ln55_1_fu_182_p3 = ((icmp_ln56_fu_150_p2[0:0] == 1'b1) ? add_ln55_fu_144_p2 : cy_fu_70);

assign select_ln55_fu_156_p3 = ((icmp_ln56_fu_150_p2[0:0] == 1'b1) ? 6'd0 : cx_fu_62);

assign select_ln56_1_fu_303_p3 = ((icmp_ln56_fu_150_p2[0:0] == 1'b1) ? 10'd1 : add_ln56_1_fu_297_p2);

assign select_ln56_fu_210_p3 = ((and_ln55_fu_176_p2[0:0] == 1'b1) ? add_ln56_fu_190_p2 : select_ln55_fu_156_p3);

assign tmp_1_fu_230_p3 = {{select_ln55_1_fu_182_p3}, {3'd0}};

assign tmp_2_fu_262_p3 = {{add_ln58_fu_252_p2}, {3'd0}};

assign tmp_fu_218_p3 = {{select_ln55_1_fu_182_p3}, {5'd0}};

assign xor_ln55_fu_164_p2 = (icmp_ln56_fu_150_p2 ^ 1'd1);

assign zext_ln57_fu_258_p1 = add_ln58_fu_252_p2;

assign zext_ln58_1_fu_238_p1 = tmp_1_fu_230_p3;

assign zext_ln58_2_fu_248_p1 = select_ln56_fu_210_p3;

assign zext_ln58_3_fu_276_p1 = b_mid2_fu_202_p3;

assign zext_ln58_4_fu_286_p1 = add_ln58_1_fu_280_p2;

assign zext_ln58_fu_226_p1 = tmp_fu_218_p3;

endmodule //ped_detect_hls_ped_detect_hls_Pipeline_VITIS_LOOP_55_1_VITIS_LOOP_56_2_VITIS_LOOP_57_3
