// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ped_detect_hls_ped_detect_hls_Pipeline_GRAD_Y_GRAD_X (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_local_address0,
        img_local_ce0,
        img_local_q0,
        img_local_address1,
        img_local_ce1,
        img_local_q1,
        img_local_address2,
        img_local_ce2,
        img_local_q2,
        img_local_address3,
        img_local_ce3,
        img_local_q3,
        hist_address0,
        hist_ce0,
        hist_we0,
        hist_d0,
        hist_address1,
        hist_ce1,
        hist_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [16:0] img_local_address0;
output   img_local_ce0;
input  [7:0] img_local_q0;
output  [16:0] img_local_address1;
output   img_local_ce1;
input  [7:0] img_local_q1;
output  [16:0] img_local_address2;
output   img_local_ce2;
input  [7:0] img_local_q2;
output  [16:0] img_local_address3;
output   img_local_ce3;
input  [7:0] img_local_q3;
output  [13:0] hist_address0;
output   hist_ce0;
output   hist_we0;
output  [31:0] hist_d0;
output  [13:0] hist_address1;
output   hist_ce1;
input  [31:0] hist_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_222_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] tmp_4_reg_807;
reg   [4:0] tmp_4_reg_807_pp0_iter2_reg;
reg   [5:0] cx_1_reg_833;
reg   [5:0] cx_1_reg_833_pp0_iter2_reg;
wire   [8:0] gx_fu_425_p2;
reg   [8:0] gx_reg_838;
wire   [7:0] trunc_ln62_fu_431_p1;
reg   [7:0] trunc_ln62_reg_843;
wire   [8:0] gy_fu_443_p2;
reg   [8:0] gy_reg_849;
wire   [7:0] trunc_ln63_fu_449_p1;
reg   [7:0] trunc_ln63_reg_854;
reg   [0:0] tmp_7_reg_860;
reg   [0:0] tmp_8_reg_865;
wire   [8:0] mag_fu_527_p2;
reg   [8:0] mag_reg_870;
reg   [13:0] hist_addr_reg_875;
wire   [0:0] addr_cmp_fu_732_p2;
reg   [0:0] addr_cmp_reg_881;
wire   [63:0] zext_ln62_fu_328_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln62_2_fu_339_p1;
wire   [63:0] zext_ln63_1_fu_360_p1;
wire   [63:0] zext_ln63_3_fu_381_p1;
wire   [63:0] zext_ln84_6_fu_724_p1;
reg   [63:0] reuse_addr_reg_fu_108;
wire    ap_loop_init;
reg   [31:0] reuse_reg_fu_112;
wire   [31:0] add_ln84_fu_756_p2;
reg   [8:0] x_fu_116;
wire   [8:0] add_ln61_fu_396_p2;
reg   [7:0] y_fu_120;
wire   [7:0] select_ln60_1_fu_260_p3;
reg   [16:0] indvar_flatten29_fu_124;
wire   [16:0] add_ln60_fu_228_p2;
reg    img_local_ce3_local;
reg    img_local_ce2_local;
reg    img_local_ce1_local;
reg    img_local_ce0_local;
reg    hist_ce1_local;
reg    hist_we0_local;
reg    hist_ce0_local;
wire   [0:0] icmp_ln61_fu_246_p2;
wire   [7:0] indvars_iv_next77_dup_fu_240_p2;
wire   [15:0] tmp_fu_268_p3;
wire   [13:0] tmp_3_fu_280_p3;
wire   [16:0] p_shl11_fu_276_p1;
wire   [16:0] p_shl12_fu_288_p1;
wire   [8:0] select_ln60_fu_252_p3;
wire   [16:0] zext_ln61_1_fu_312_p1;
wire   [16:0] empty_fu_292_p2;
wire   [16:0] add_ln62_fu_316_p2;
wire   [16:0] add_ln62_1_fu_322_p2;
wire   [16:0] add_ln62_2_fu_333_p2;
wire   [9:0] zext_ln61_fu_308_p1;
wire   [9:0] add_ln63_2_fu_344_p2;
wire   [16:0] zext_ln63_fu_350_p1;
wire   [16:0] add_ln63_fu_354_p2;
wire   [9:0] add_ln63_3_fu_365_p2;
wire  signed [16:0] sext_ln63_fu_371_p1;
wire   [16:0] add_ln63_1_fu_375_p2;
wire   [8:0] zext_ln62_1_fu_417_p1;
wire   [8:0] zext_ln62_3_fu_421_p1;
wire   [8:0] zext_ln63_2_fu_435_p1;
wire   [8:0] zext_ln63_4_fu_439_p1;
wire   [9:0] tmp_5_fu_469_p3;
wire   [7:0] tmp_6_fu_480_p3;
wire   [10:0] zext_ln84_fu_476_p1;
wire   [10:0] zext_ln84_2_fu_487_p1;
wire   [7:0] sub_ln31_fu_497_p2;
wire   [7:0] ax_fu_502_p3;
wire   [7:0] sub_ln31_1_fu_512_p2;
wire   [7:0] ay_fu_517_p3;
wire   [8:0] zext_ln65_fu_523_p1;
wire   [8:0] zext_ln31_fu_508_p1;
wire   [6:0] tmp_9_fu_533_p4;
wire   [8:0] shl_ln_fu_549_p3;
wire   [0:0] icmp_ln73_fu_563_p2;
wire   [8:0] shl_ln1_fu_576_p3;
wire   [0:0] icmp_ln77_fu_590_p2;
wire   [2:0] bin_1_fu_595_p3;
wire   [2:0] bin_2_fu_603_p3;
wire   [2:0] bin_4_fu_611_p3;
wire   [0:0] icmp_ln70_fu_543_p2;
wire   [0:0] icmp_ln72_fu_557_p2;
wire   [0:0] xor_ln70_fu_623_p2;
wire   [0:0] or_ln72_fu_635_p2;
wire   [0:0] icmp_ln74_fu_584_p2;
wire   [0:0] xor_ln72_fu_641_p2;
wire   [0:0] and_ln72_fu_629_p2;
wire   [0:0] and_ln74_fu_647_p2;
wire   [3:0] bin_3_fu_663_p4;
wire   [3:0] bin_3_fu_663_p8;
wire   [3:0] bin_3_fu_663_p9;
wire   [2:0] bin_3_fu_663_p10;
wire   [10:0] add_ln84_3_fu_491_p2;
wire   [10:0] zext_ln84_3_fu_687_p1;
wire   [10:0] add_ln84_1_fu_690_p2;
wire   [13:0] tmp_10_fu_700_p3;
wire   [13:0] zext_ln84_4_fu_696_p1;
wire   [3:0] bin_3_fu_663_p11;
wire   [13:0] add_ln84_4_fu_708_p2;
wire   [13:0] zext_ln84_5_fu_714_p1;
wire   [13:0] add_ln84_2_fu_718_p2;
wire   [31:0] reuse_select_fu_749_p3;
wire   [31:0] zext_ln84_1_fu_743_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [2:0] bin_3_fu_663_p1;
wire   [2:0] bin_3_fu_663_p3;
wire   [2:0] bin_3_fu_663_p5;
wire   [2:0] bin_3_fu_663_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 reuse_addr_reg_fu_108 = 64'd0;
#0 reuse_reg_fu_112 = 32'd0;
#0 x_fu_116 = 9'd0;
#0 y_fu_120 = 8'd0;
#0 indvar_flatten29_fu_124 = 17'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ped_detect_hls_sparsemux_9_3_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 4 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 4 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 4 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 4 ),
    .def_WIDTH( 4 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 4 ))
sparsemux_9_3_4_1_1_U5(
    .din0(4'd0),
    .din1(bin_3_fu_663_p4),
    .din2(4'd4),
    .din3(bin_3_fu_663_p8),
    .def(bin_3_fu_663_p9),
    .sel(bin_3_fu_663_p10),
    .dout(bin_3_fu_663_p11)
);

ped_detect_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten29_fu_124 <= 17'd0;
        end else if (((icmp_ln60_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten29_fu_124 <= add_ln60_fu_228_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            reuse_addr_reg_fu_108 <= 64'd18446744073709551615;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            reuse_addr_reg_fu_108 <= zext_ln84_6_fu_724_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            reuse_reg_fu_112 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            reuse_reg_fu_112 <= add_ln84_fu_756_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_116 <= 9'd1;
        end else if (((icmp_ln60_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            x_fu_116 <= add_ln61_fu_396_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            y_fu_120 <= 8'd1;
        end else if (((icmp_ln60_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            y_fu_120 <= select_ln60_1_fu_260_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        addr_cmp_reg_881 <= addr_cmp_fu_732_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        cx_1_reg_833_pp0_iter2_reg <= cx_1_reg_833;
        gx_reg_838 <= gx_fu_425_p2;
        gy_reg_849 <= gy_fu_443_p2;
        hist_addr_reg_875 <= zext_ln84_6_fu_724_p1;
        mag_reg_870 <= mag_fu_527_p2;
        tmp_4_reg_807_pp0_iter2_reg <= tmp_4_reg_807;
        tmp_7_reg_860 <= gx_fu_425_p2[32'd8];
        tmp_8_reg_865 <= gy_fu_443_p2[32'd8];
        trunc_ln62_reg_843 <= trunc_ln62_fu_431_p1;
        trunc_ln63_reg_854 <= trunc_ln63_fu_449_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        cx_1_reg_833 <= {{select_ln60_fu_252_p3[8:3]}};
        tmp_4_reg_807 <= {{select_ln60_1_fu_260_p3[7:3]}};
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_222_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        hist_ce0_local = 1'b1;
    end else begin
        hist_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        hist_ce1_local = 1'b1;
    end else begin
        hist_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        hist_we0_local = 1'b1;
    end else begin
        hist_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_local_ce0_local = 1'b1;
    end else begin
        img_local_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_local_ce1_local = 1'b1;
    end else begin
        img_local_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_local_ce2_local = 1'b1;
    end else begin
        img_local_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_local_ce3_local = 1'b1;
    end else begin
        img_local_ce3_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_228_p2 = (indvar_flatten29_fu_124 + 17'd1);

assign add_ln61_fu_396_p2 = (select_ln60_fu_252_p3 + 9'd1);

assign add_ln62_1_fu_322_p2 = (add_ln62_fu_316_p2 + 17'd1);

assign add_ln62_2_fu_333_p2 = ($signed(add_ln62_fu_316_p2) + $signed(17'd131071));

assign add_ln62_fu_316_p2 = (zext_ln61_1_fu_312_p1 + empty_fu_292_p2);

assign add_ln63_1_fu_375_p2 = ($signed(sext_ln63_fu_371_p1) + $signed(empty_fu_292_p2));

assign add_ln63_2_fu_344_p2 = (zext_ln61_fu_308_p1 + 10'd320);

assign add_ln63_3_fu_365_p2 = ($signed(zext_ln61_fu_308_p1) + $signed(10'd704));

assign add_ln63_fu_354_p2 = (zext_ln63_fu_350_p1 + empty_fu_292_p2);

assign add_ln84_1_fu_690_p2 = (add_ln84_3_fu_491_p2 + zext_ln84_3_fu_687_p1);

assign add_ln84_2_fu_718_p2 = (add_ln84_4_fu_708_p2 + zext_ln84_5_fu_714_p1);

assign add_ln84_3_fu_491_p2 = (zext_ln84_fu_476_p1 + zext_ln84_2_fu_487_p1);

assign add_ln84_4_fu_708_p2 = (tmp_10_fu_700_p3 + zext_ln84_4_fu_696_p1);

assign add_ln84_fu_756_p2 = (reuse_select_fu_749_p3 + zext_ln84_1_fu_743_p1);

assign addr_cmp_fu_732_p2 = ((reuse_addr_reg_fu_108 == zext_ln84_6_fu_724_p1) ? 1'b1 : 1'b0);

assign and_ln72_fu_629_p2 = (xor_ln70_fu_623_p2 & icmp_ln72_fu_557_p2);

assign and_ln74_fu_647_p2 = (xor_ln72_fu_641_p2 & icmp_ln74_fu_584_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign ax_fu_502_p3 = ((tmp_7_reg_860[0:0] == 1'b1) ? sub_ln31_fu_497_p2 : trunc_ln62_reg_843);

assign ay_fu_517_p3 = ((tmp_8_reg_865[0:0] == 1'b1) ? sub_ln31_1_fu_512_p2 : trunc_ln63_reg_854);

assign bin_1_fu_595_p3 = ((icmp_ln77_fu_590_p2[0:0] == 1'b1) ? 3'd2 : 3'd6);

assign bin_2_fu_603_p3 = ((icmp_ln77_fu_590_p2[0:0] == 1'b1) ? 3'd6 : 3'd2);

assign bin_3_fu_663_p10 = {{{icmp_ln70_fu_543_p2}, {and_ln72_fu_629_p2}}, {and_ln74_fu_647_p2}};

assign bin_3_fu_663_p4 = ((icmp_ln73_fu_563_p2[0:0] == 1'b1) ? 4'd0 : 4'd8);

assign bin_3_fu_663_p8 = bin_4_fu_611_p3;

assign bin_3_fu_663_p9 = 'bx;

assign bin_4_fu_611_p3 = ((icmp_ln73_fu_563_p2[0:0] == 1'b1) ? bin_1_fu_595_p3 : bin_2_fu_603_p3);

assign empty_fu_292_p2 = (p_shl11_fu_276_p1 + p_shl12_fu_288_p1);

assign gx_fu_425_p2 = (zext_ln62_1_fu_417_p1 - zext_ln62_3_fu_421_p1);

assign gy_fu_443_p2 = (zext_ln63_2_fu_435_p1 - zext_ln63_4_fu_439_p1);

assign hist_address0 = hist_addr_reg_875;

assign hist_address1 = zext_ln84_6_fu_724_p1;

assign hist_ce0 = hist_ce0_local;

assign hist_ce1 = hist_ce1_local;

assign hist_d0 = add_ln84_fu_756_p2;

assign hist_we0 = hist_we0_local;

assign icmp_ln60_fu_222_p2 = ((indvar_flatten29_fu_124 == 17'd75684) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_246_p2 = ((x_fu_116 == 9'd319) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_543_p2 = ((tmp_9_fu_533_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_557_p2 = ((shl_ln_fu_549_p3 < zext_ln31_fu_508_p1) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_563_p2 = (($signed(gx_reg_838) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_584_p2 = ((shl_ln1_fu_576_p3 < zext_ln65_fu_523_p1) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_590_p2 = (($signed(gy_reg_849) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign img_local_address0 = zext_ln63_3_fu_381_p1;

assign img_local_address1 = zext_ln63_1_fu_360_p1;

assign img_local_address2 = zext_ln62_2_fu_339_p1;

assign img_local_address3 = zext_ln62_fu_328_p1;

assign img_local_ce0 = img_local_ce0_local;

assign img_local_ce1 = img_local_ce1_local;

assign img_local_ce2 = img_local_ce2_local;

assign img_local_ce3 = img_local_ce3_local;

assign indvars_iv_next77_dup_fu_240_p2 = (y_fu_120 + 8'd1);

assign mag_fu_527_p2 = (zext_ln65_fu_523_p1 + zext_ln31_fu_508_p1);

assign or_ln72_fu_635_p2 = (icmp_ln72_fu_557_p2 | icmp_ln70_fu_543_p2);

assign p_shl11_fu_276_p1 = tmp_fu_268_p3;

assign p_shl12_fu_288_p1 = tmp_3_fu_280_p3;

assign reuse_select_fu_749_p3 = ((addr_cmp_reg_881[0:0] == 1'b1) ? reuse_reg_fu_112 : hist_q1);

assign select_ln60_1_fu_260_p3 = ((icmp_ln61_fu_246_p2[0:0] == 1'b1) ? indvars_iv_next77_dup_fu_240_p2 : y_fu_120);

assign select_ln60_fu_252_p3 = ((icmp_ln61_fu_246_p2[0:0] == 1'b1) ? 9'd1 : x_fu_116);

assign sext_ln63_fu_371_p1 = $signed(add_ln63_3_fu_365_p2);

assign shl_ln1_fu_576_p3 = {{ax_fu_502_p3}, {1'd0}};

assign shl_ln_fu_549_p3 = {{ay_fu_517_p3}, {1'd0}};

assign sub_ln31_1_fu_512_p2 = (8'd0 - trunc_ln63_reg_854);

assign sub_ln31_fu_497_p2 = (8'd0 - trunc_ln62_reg_843);

assign tmp_10_fu_700_p3 = {{add_ln84_1_fu_690_p2}, {3'd0}};

assign tmp_3_fu_280_p3 = {{select_ln60_1_fu_260_p3}, {6'd0}};

assign tmp_5_fu_469_p3 = {{tmp_4_reg_807_pp0_iter2_reg}, {5'd0}};

assign tmp_6_fu_480_p3 = {{tmp_4_reg_807_pp0_iter2_reg}, {3'd0}};

assign tmp_9_fu_533_p4 = {{mag_fu_527_p2[8:2]}};

assign tmp_fu_268_p3 = {{select_ln60_1_fu_260_p3}, {8'd0}};

assign trunc_ln62_fu_431_p1 = gx_fu_425_p2[7:0];

assign trunc_ln63_fu_449_p1 = gy_fu_443_p2[7:0];

assign xor_ln70_fu_623_p2 = (icmp_ln70_fu_543_p2 ^ 1'd1);

assign xor_ln72_fu_641_p2 = (or_ln72_fu_635_p2 ^ 1'd1);

assign zext_ln31_fu_508_p1 = ax_fu_502_p3;

assign zext_ln61_1_fu_312_p1 = select_ln60_fu_252_p3;

assign zext_ln61_fu_308_p1 = select_ln60_fu_252_p3;

assign zext_ln62_1_fu_417_p1 = img_local_q3;

assign zext_ln62_2_fu_339_p1 = add_ln62_2_fu_333_p2;

assign zext_ln62_3_fu_421_p1 = img_local_q2;

assign zext_ln62_fu_328_p1 = add_ln62_1_fu_322_p2;

assign zext_ln63_1_fu_360_p1 = add_ln63_fu_354_p2;

assign zext_ln63_2_fu_435_p1 = img_local_q1;

assign zext_ln63_3_fu_381_p1 = add_ln63_1_fu_375_p2;

assign zext_ln63_4_fu_439_p1 = img_local_q0;

assign zext_ln63_fu_350_p1 = add_ln63_2_fu_344_p2;

assign zext_ln65_fu_523_p1 = ay_fu_517_p3;

assign zext_ln84_1_fu_743_p1 = mag_reg_870;

assign zext_ln84_2_fu_487_p1 = tmp_6_fu_480_p3;

assign zext_ln84_3_fu_687_p1 = cx_1_reg_833_pp0_iter2_reg;

assign zext_ln84_4_fu_696_p1 = add_ln84_1_fu_690_p2;

assign zext_ln84_5_fu_714_p1 = bin_3_fu_663_p11;

assign zext_ln84_6_fu_724_p1 = add_ln84_2_fu_718_p2;

assign zext_ln84_fu_476_p1 = tmp_5_fu_469_p3;

endmodule //ped_detect_hls_ped_detect_hls_Pipeline_GRAD_Y_GRAD_X
