// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_tinylenet_hls_cnn_tinylenet_hls_Pipeline_POOL2_OC_POOL2_OH_POOL2_OW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_q0,
        conv2_out_address1,
        conv2_out_ce1,
        conv2_out_q1,
        conv2_out_1_address0,
        conv2_out_1_ce0,
        conv2_out_1_q0,
        conv2_out_1_address1,
        conv2_out_1_ce1,
        conv2_out_1_q1,
        pool2_out_address0,
        pool2_out_ce0,
        pool2_out_we0,
        pool2_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] conv2_out_address0;
output   conv2_out_ce0;
input  [14:0] conv2_out_q0;
output  [8:0] conv2_out_address1;
output   conv2_out_ce1;
input  [14:0] conv2_out_q1;
output  [8:0] conv2_out_1_address0;
output   conv2_out_1_ce0;
input  [14:0] conv2_out_1_q0;
output  [8:0] conv2_out_1_address1;
output   conv2_out_1_ce1;
input  [14:0] conv2_out_1_q1;
output  [7:0] pool2_out_address0;
output   pool2_out_ce0;
output   pool2_out_we0;
output  [14:0] pool2_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln126_fu_169_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] add_ln134_1_fu_347_p2;
reg   [7:0] add_ln134_1_reg_503;
wire   [63:0] zext_ln130_fu_329_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln132_fu_341_p1;
wire   [63:0] zext_ln134_1_fu_398_p1;
reg   [2:0] ow_fu_58;
wire   [2:0] add_ln128_fu_353_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_ow_load;
reg   [2:0] oh_fu_62;
wire   [2:0] select_ln127_fu_263_p3;
reg   [2:0] ap_sig_allocacmp_oh_load;
reg   [5:0] indvar_flatten307_fu_66;
wire   [5:0] select_ln127_1_fu_365_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten307_load;
reg   [4:0] oc_fu_70;
wire   [4:0] select_ln126_1_fu_231_p3;
reg   [4:0] ap_sig_allocacmp_oc_load;
reg   [8:0] indvar_flatten320_fu_74;
wire   [8:0] add_ln126_1_fu_175_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten320_load;
reg    conv2_out_ce1_local;
reg    conv2_out_ce0_local;
reg    conv2_out_1_ce1_local;
reg    conv2_out_1_ce0_local;
reg    pool2_out_we0_local;
wire   [14:0] mx_4_fu_436_p3;
reg    pool2_out_ce0_local;
wire   [0:0] icmp_ln127_fu_199_p2;
wire   [0:0] icmp_ln128_fu_219_p2;
wire   [0:0] xor_ln126_fu_213_p2;
wire   [4:0] add_ln126_fu_193_p2;
wire   [2:0] select_ln126_fu_205_p3;
wire   [0:0] and_ln126_fu_225_p2;
wire   [0:0] empty_fu_249_p2;
wire   [2:0] add_ln127_fu_243_p2;
wire   [3:0] trunc_ln127_fu_239_p1;
wire   [5:0] tmp_3_fu_271_p3;
wire   [5:0] zext_ln134_fu_279_p1;
wire   [5:0] add_ln134_fu_283_p2;
wire   [1:0] empty_33_fu_297_p1;
wire   [2:0] ow_4_mid2_fu_255_p3;
wire   [8:0] tmp_8_fu_319_p4;
wire   [8:0] tmp_7_fu_301_p4;
wire   [8:0] zext_ln130_2_fu_315_p1;
wire   [8:0] add_ln132_fu_335_p2;
wire   [7:0] tmp_fu_289_p3;
wire   [7:0] zext_ln130_1_fu_311_p1;
wire   [5:0] add_ln127_1_fu_359_p2;
wire   [0:0] icmp_ln131_fu_402_p2;
wire   [14:0] mx_1_fu_408_p3;
wire   [0:0] icmp_ln132_fu_416_p2;
wire   [14:0] mx_3_fu_422_p3;
wire   [0:0] icmp_ln133_fu_430_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ow_fu_58 = 3'd0;
#0 oh_fu_62 = 3'd0;
#0 indvar_flatten307_fu_66 = 6'd0;
#0 oc_fu_70 = 5'd0;
#0 indvar_flatten320_fu_74 = 9'd0;
#0 ap_done_reg = 1'b0;
end

cnn_tinylenet_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten307_fu_66 <= select_ln127_1_fu_365_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten307_fu_66 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten320_fu_74 <= add_ln126_1_fu_175_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten320_fu_74 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oc_fu_70 <= select_ln126_1_fu_231_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_70 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oh_fu_62 <= select_ln127_fu_263_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oh_fu_62 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_169_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ow_fu_58 <= add_ln128_fu_353_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ow_fu_58 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln134_1_reg_503 <= add_ln134_1_fu_347_p2;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_169_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten307_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten307_load = indvar_flatten307_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten320_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten320_load = indvar_flatten320_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oc_load = 5'd0;
    end else begin
        ap_sig_allocacmp_oc_load = oc_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oh_load = 3'd0;
    end else begin
        ap_sig_allocacmp_oh_load = oh_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ow_load = 3'd0;
    end else begin
        ap_sig_allocacmp_ow_load = ow_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_1_ce0_local = 1'b1;
    end else begin
        conv2_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_1_ce1_local = 1'b1;
    end else begin
        conv2_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv2_out_ce1_local = 1'b1;
    end else begin
        conv2_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_out_ce0_local = 1'b1;
    end else begin
        pool2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool2_out_we0_local = 1'b1;
    end else begin
        pool2_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_1_fu_175_p2 = (ap_sig_allocacmp_indvar_flatten320_load + 9'd1);

assign add_ln126_fu_193_p2 = (ap_sig_allocacmp_oc_load + 5'd1);

assign add_ln127_1_fu_359_p2 = (ap_sig_allocacmp_indvar_flatten307_load + 6'd1);

assign add_ln127_fu_243_p2 = (select_ln126_fu_205_p3 + 3'd1);

assign add_ln128_fu_353_p2 = (ow_4_mid2_fu_255_p3 + 3'd1);

assign add_ln132_fu_335_p2 = (tmp_7_fu_301_p4 + zext_ln130_2_fu_315_p1);

assign add_ln134_1_fu_347_p2 = (tmp_fu_289_p3 + zext_ln130_1_fu_311_p1);

assign add_ln134_fu_283_p2 = (tmp_3_fu_271_p3 + zext_ln134_fu_279_p1);

assign and_ln126_fu_225_p2 = (xor_ln126_fu_213_p2 & icmp_ln128_fu_219_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv2_out_1_address0 = zext_ln132_fu_341_p1;

assign conv2_out_1_address1 = zext_ln130_fu_329_p1;

assign conv2_out_1_ce0 = conv2_out_1_ce0_local;

assign conv2_out_1_ce1 = conv2_out_1_ce1_local;

assign conv2_out_address0 = zext_ln132_fu_341_p1;

assign conv2_out_address1 = zext_ln130_fu_329_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign conv2_out_ce1 = conv2_out_ce1_local;

assign empty_33_fu_297_p1 = select_ln127_fu_263_p3[1:0];

assign empty_fu_249_p2 = (icmp_ln127_fu_199_p2 | and_ln126_fu_225_p2);

assign icmp_ln126_fu_169_p2 = ((ap_sig_allocacmp_indvar_flatten320_load == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_199_p2 = ((ap_sig_allocacmp_indvar_flatten307_load == 6'd16) ? 1'b1 : 1'b0);

assign icmp_ln128_fu_219_p2 = ((ap_sig_allocacmp_ow_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_402_p2 = ((conv2_out_1_q1 > conv2_out_q1) ? 1'b1 : 1'b0);

assign icmp_ln132_fu_416_p2 = ((conv2_out_q0 > mx_1_fu_408_p3) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_430_p2 = ((conv2_out_1_q0 > mx_3_fu_422_p3) ? 1'b1 : 1'b0);

assign mx_1_fu_408_p3 = ((icmp_ln131_fu_402_p2[0:0] == 1'b1) ? conv2_out_1_q1 : conv2_out_q1);

assign mx_3_fu_422_p3 = ((icmp_ln132_fu_416_p2[0:0] == 1'b1) ? conv2_out_q0 : mx_1_fu_408_p3);

assign mx_4_fu_436_p3 = ((icmp_ln133_fu_430_p2[0:0] == 1'b1) ? conv2_out_1_q0 : mx_3_fu_422_p3);

assign ow_4_mid2_fu_255_p3 = ((empty_fu_249_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_ow_load);

assign pool2_out_address0 = zext_ln134_1_fu_398_p1;

assign pool2_out_ce0 = pool2_out_ce0_local;

assign pool2_out_d0 = mx_4_fu_436_p3;

assign pool2_out_we0 = pool2_out_we0_local;

assign select_ln126_1_fu_231_p3 = ((icmp_ln127_fu_199_p2[0:0] == 1'b1) ? add_ln126_fu_193_p2 : ap_sig_allocacmp_oc_load);

assign select_ln126_fu_205_p3 = ((icmp_ln127_fu_199_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_oh_load);

assign select_ln127_1_fu_365_p3 = ((icmp_ln127_fu_199_p2[0:0] == 1'b1) ? 6'd1 : add_ln127_1_fu_359_p2);

assign select_ln127_fu_263_p3 = ((and_ln126_fu_225_p2[0:0] == 1'b1) ? add_ln127_fu_243_p2 : select_ln126_fu_205_p3);

assign tmp_3_fu_271_p3 = {{trunc_ln127_fu_239_p1}, {2'd0}};

assign tmp_7_fu_301_p4 = {{{trunc_ln127_fu_239_p1}, {empty_33_fu_297_p1}}, {3'd4}};

assign tmp_8_fu_319_p4 = {{{trunc_ln127_fu_239_p1}, {empty_33_fu_297_p1}}, {ow_4_mid2_fu_255_p3}};

assign tmp_fu_289_p3 = {{add_ln134_fu_283_p2}, {2'd0}};

assign trunc_ln127_fu_239_p1 = select_ln126_1_fu_231_p3[3:0];

assign xor_ln126_fu_213_p2 = (icmp_ln127_fu_199_p2 ^ 1'd1);

assign zext_ln130_1_fu_311_p1 = ow_4_mid2_fu_255_p3;

assign zext_ln130_2_fu_315_p1 = ow_4_mid2_fu_255_p3;

assign zext_ln130_fu_329_p1 = tmp_8_fu_319_p4;

assign zext_ln132_fu_341_p1 = add_ln132_fu_335_p2;

assign zext_ln134_1_fu_398_p1 = add_ln134_1_reg_503;

assign zext_ln134_fu_279_p1 = select_ln127_fu_263_p3;

endmodule //cnn_tinylenet_hls_cnn_tinylenet_hls_Pipeline_POOL2_OC_POOL2_OH_POOL2_OW
