// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_tinylenet_hls_cnn_tinylenet_hls_Pipeline_POOL1_OC_POOL1_OH_POOL1_OW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_q0,
        conv1_out_address1,
        conv1_out_ce1,
        conv1_out_q1,
        conv1_out_1_address0,
        conv1_out_1_ce0,
        conv1_out_1_q0,
        conv1_out_1_address1,
        conv1_out_1_ce1,
        conv1_out_1_q1,
        pool1_out_address0,
        pool1_out_ce0,
        pool1_out_we0,
        pool1_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] conv1_out_address0;
output   conv1_out_ce0;
input  [11:0] conv1_out_q0;
output  [11:0] conv1_out_address1;
output   conv1_out_ce1;
input  [11:0] conv1_out_q1;
output  [11:0] conv1_out_1_address0;
output   conv1_out_1_ce0;
input  [11:0] conv1_out_1_q0;
output  [11:0] conv1_out_1_address1;
output   conv1_out_1_ce1;
input  [11:0] conv1_out_1_q1;
output  [10:0] pool1_out_address0;
output   pool1_out_ce0;
output   pool1_out_we0;
output  [11:0] pool1_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln87_fu_183_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] add_ln95_1_fu_501_p2;
reg   [10:0] add_ln95_1_reg_657;
wire   [63:0] zext_ln91_5_fu_483_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln93_2_fu_495_p1;
wire   [63:0] zext_ln95_3_fu_552_p1;
reg   [3:0] ow_fu_72;
wire   [3:0] add_ln89_fu_507_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_ow_load;
reg   [3:0] oh_fu_76;
wire   [3:0] select_ln88_fu_273_p3;
reg   [3:0] ap_sig_allocacmp_oh_load;
reg   [7:0] indvar_flatten_fu_80;
wire   [7:0] select_ln88_1_fu_519_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [3:0] oc_fu_84;
wire   [3:0] select_ln87_1_fu_245_p3;
reg   [3:0] ap_sig_allocacmp_oc_load;
reg   [10:0] indvar_flatten156_fu_88;
wire   [10:0] add_ln87_1_fu_189_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten156_load;
reg    conv1_out_ce1_local;
reg    conv1_out_ce0_local;
reg    conv1_out_1_ce1_local;
reg    conv1_out_1_ce0_local;
reg    pool1_out_we0_local;
wire   [11:0] mx_8_fu_590_p3;
reg    pool1_out_ce0_local;
wire   [0:0] icmp_ln88_fu_213_p2;
wire   [0:0] icmp_ln89_fu_233_p2;
wire   [0:0] xor_ln87_fu_227_p2;
wire   [3:0] add_ln87_fu_207_p2;
wire   [3:0] select_ln87_fu_219_p3;
wire   [0:0] and_ln87_fu_239_p2;
wire   [0:0] empty_fu_259_p2;
wire   [3:0] add_ln88_fu_253_p2;
wire   [6:0] tmp_2_fu_289_p3;
wire   [8:0] p_shl_fu_281_p3;
wire   [8:0] zext_ln91_fu_297_p1;
wire   [5:0] tmp_3_fu_315_p3;
wire   [7:0] p_shl1_fu_307_p3;
wire   [7:0] zext_ln95_fu_323_p1;
wire   [7:0] sub_ln95_fu_327_p2;
wire   [7:0] zext_ln95_1_fu_333_p1;
wire   [7:0] add_ln95_fu_337_p2;
wire   [6:0] trunc_ln95_fu_343_p1;
wire   [9:0] tmp_4_fu_347_p3;
wire   [10:0] tmp_5_fu_355_p3;
wire   [10:0] zext_ln95_2_fu_363_p1;
wire   [4:0] tmp_fu_373_p3;
wire   [8:0] sub_ln91_fu_301_p2;
wire   [8:0] zext_ln91_1_fu_381_p1;
wire   [8:0] add_ln91_fu_385_p2;
wire   [7:0] trunc_ln91_fu_391_p1;
wire   [10:0] tmp_6_fu_395_p3;
wire   [11:0] tmp_7_fu_403_p3;
wire   [11:0] zext_ln91_2_fu_411_p1;
wire   [4:0] tmp_1_fu_421_p3;
wire   [8:0] zext_ln93_fu_429_p1;
wire   [8:0] add_ln93_fu_433_p2;
wire   [7:0] trunc_ln93_fu_439_p1;
wire   [10:0] tmp_8_fu_443_p3;
wire   [11:0] tmp_9_fu_451_p3;
wire   [11:0] zext_ln93_1_fu_459_p1;
wire   [3:0] ow_1_mid2_fu_265_p3;
wire   [11:0] sub_ln91_1_fu_415_p2;
wire   [11:0] zext_ln91_4_fu_473_p1;
wire   [11:0] add_ln91_1_fu_477_p2;
wire   [11:0] sub_ln89_fu_463_p2;
wire   [11:0] add_ln93_1_fu_489_p2;
wire   [10:0] sub_ln95_1_fu_367_p2;
wire   [10:0] zext_ln91_3_fu_469_p1;
wire   [7:0] add_ln88_1_fu_513_p2;
wire   [0:0] icmp_ln92_fu_556_p2;
wire   [11:0] mx_5_fu_562_p3;
wire   [0:0] icmp_ln93_fu_570_p2;
wire   [11:0] mx_7_fu_576_p3;
wire   [0:0] icmp_ln94_fu_584_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ow_fu_72 = 4'd0;
#0 oh_fu_76 = 4'd0;
#0 indvar_flatten_fu_80 = 8'd0;
#0 oc_fu_84 = 4'd0;
#0 indvar_flatten156_fu_88 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_tinylenet_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten156_fu_88 <= add_ln87_1_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten156_fu_88 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_80 <= select_ln88_1_fu_519_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_80 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oc_fu_84 <= select_ln87_1_fu_245_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_84 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oh_fu_76 <= select_ln88_fu_273_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oh_fu_76 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln87_fu_183_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ow_fu_72 <= add_ln89_fu_507_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ow_fu_72 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln95_1_reg_657 <= add_ln95_1_fu_501_p2;
    end
end

always @ (*) begin
    if (((icmp_ln87_fu_183_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten156_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten156_load = indvar_flatten156_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oc_load = 4'd0;
    end else begin
        ap_sig_allocacmp_oc_load = oc_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_oh_load = 4'd0;
    end else begin
        ap_sig_allocacmp_oh_load = oh_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ow_load = 4'd0;
    end else begin
        ap_sig_allocacmp_ow_load = ow_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_1_ce0_local = 1'b1;
    end else begin
        conv1_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_1_ce1_local = 1'b1;
    end else begin
        conv1_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_out_ce1_local = 1'b1;
    end else begin
        conv1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_ce0_local = 1'b1;
    end else begin
        pool1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pool1_out_we0_local = 1'b1;
    end else begin
        pool1_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln87_1_fu_189_p2 = (ap_sig_allocacmp_indvar_flatten156_load + 11'd1);

assign add_ln87_fu_207_p2 = (ap_sig_allocacmp_oc_load + 4'd1);

assign add_ln88_1_fu_513_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln88_fu_253_p2 = (select_ln87_fu_219_p3 + 4'd1);

assign add_ln89_fu_507_p2 = (ow_1_mid2_fu_265_p3 + 4'd1);

assign add_ln91_1_fu_477_p2 = (sub_ln91_1_fu_415_p2 + zext_ln91_4_fu_473_p1);

assign add_ln91_fu_385_p2 = (sub_ln91_fu_301_p2 + zext_ln91_1_fu_381_p1);

assign add_ln93_1_fu_489_p2 = (sub_ln89_fu_463_p2 + zext_ln91_4_fu_473_p1);

assign add_ln93_fu_433_p2 = (sub_ln91_fu_301_p2 + zext_ln93_fu_429_p1);

assign add_ln95_1_fu_501_p2 = (sub_ln95_1_fu_367_p2 + zext_ln91_3_fu_469_p1);

assign add_ln95_fu_337_p2 = (sub_ln95_fu_327_p2 + zext_ln95_1_fu_333_p1);

assign and_ln87_fu_239_p2 = (xor_ln87_fu_227_p2 & icmp_ln89_fu_233_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv1_out_1_address0 = zext_ln93_2_fu_495_p1;

assign conv1_out_1_address1 = zext_ln91_5_fu_483_p1;

assign conv1_out_1_ce0 = conv1_out_1_ce0_local;

assign conv1_out_1_ce1 = conv1_out_1_ce1_local;

assign conv1_out_address0 = zext_ln93_2_fu_495_p1;

assign conv1_out_address1 = zext_ln91_5_fu_483_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_ce1 = conv1_out_ce1_local;

assign empty_fu_259_p2 = (icmp_ln88_fu_213_p2 | and_ln87_fu_239_p2);

assign icmp_ln87_fu_183_p2 = ((ap_sig_allocacmp_indvar_flatten156_load == 11'd1152) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_213_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_233_p2 = ((ap_sig_allocacmp_ow_load == 4'd12) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_556_p2 = ((conv1_out_1_q1 > conv1_out_q1) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_570_p2 = ((conv1_out_q0 > mx_5_fu_562_p3) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_584_p2 = ((conv1_out_1_q0 > mx_7_fu_576_p3) ? 1'b1 : 1'b0);

assign mx_5_fu_562_p3 = ((icmp_ln92_fu_556_p2[0:0] == 1'b1) ? conv1_out_1_q1 : conv1_out_q1);

assign mx_7_fu_576_p3 = ((icmp_ln93_fu_570_p2[0:0] == 1'b1) ? conv1_out_q0 : mx_5_fu_562_p3);

assign mx_8_fu_590_p3 = ((icmp_ln94_fu_584_p2[0:0] == 1'b1) ? conv1_out_1_q0 : mx_7_fu_576_p3);

assign ow_1_mid2_fu_265_p3 = ((empty_fu_259_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_ow_load);

assign p_shl1_fu_307_p3 = {{select_ln87_1_fu_245_p3}, {4'd0}};

assign p_shl_fu_281_p3 = {{select_ln87_1_fu_245_p3}, {5'd0}};

assign pool1_out_address0 = zext_ln95_3_fu_552_p1;

assign pool1_out_ce0 = pool1_out_ce0_local;

assign pool1_out_d0 = mx_8_fu_590_p3;

assign pool1_out_we0 = pool1_out_we0_local;

assign select_ln87_1_fu_245_p3 = ((icmp_ln88_fu_213_p2[0:0] == 1'b1) ? add_ln87_fu_207_p2 : ap_sig_allocacmp_oc_load);

assign select_ln87_fu_219_p3 = ((icmp_ln88_fu_213_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_oh_load);

assign select_ln88_1_fu_519_p3 = ((icmp_ln88_fu_213_p2[0:0] == 1'b1) ? 8'd1 : add_ln88_1_fu_513_p2);

assign select_ln88_fu_273_p3 = ((and_ln87_fu_239_p2[0:0] == 1'b1) ? add_ln88_fu_253_p2 : select_ln87_fu_219_p3);

assign sub_ln89_fu_463_p2 = (tmp_9_fu_451_p3 - zext_ln93_1_fu_459_p1);

assign sub_ln91_1_fu_415_p2 = (tmp_7_fu_403_p3 - zext_ln91_2_fu_411_p1);

assign sub_ln91_fu_301_p2 = (p_shl_fu_281_p3 - zext_ln91_fu_297_p1);

assign sub_ln95_1_fu_367_p2 = (tmp_5_fu_355_p3 - zext_ln95_2_fu_363_p1);

assign sub_ln95_fu_327_p2 = (p_shl1_fu_307_p3 - zext_ln95_fu_323_p1);

assign tmp_1_fu_421_p3 = {{select_ln88_fu_273_p3}, {1'd1}};

assign tmp_2_fu_289_p3 = {{select_ln87_1_fu_245_p3}, {3'd0}};

assign tmp_3_fu_315_p3 = {{select_ln87_1_fu_245_p3}, {2'd0}};

assign tmp_4_fu_347_p3 = {{add_ln95_fu_337_p2}, {2'd0}};

assign tmp_5_fu_355_p3 = {{trunc_ln95_fu_343_p1}, {4'd0}};

assign tmp_6_fu_395_p3 = {{add_ln91_fu_385_p2}, {2'd0}};

assign tmp_7_fu_403_p3 = {{trunc_ln91_fu_391_p1}, {4'd0}};

assign tmp_8_fu_443_p3 = {{add_ln93_fu_433_p2}, {2'd0}};

assign tmp_9_fu_451_p3 = {{trunc_ln93_fu_439_p1}, {4'd0}};

assign tmp_fu_373_p3 = {{select_ln88_fu_273_p3}, {1'd0}};

assign trunc_ln91_fu_391_p1 = add_ln91_fu_385_p2[7:0];

assign trunc_ln93_fu_439_p1 = add_ln93_fu_433_p2[7:0];

assign trunc_ln95_fu_343_p1 = add_ln95_fu_337_p2[6:0];

assign xor_ln87_fu_227_p2 = (icmp_ln88_fu_213_p2 ^ 1'd1);

assign zext_ln91_1_fu_381_p1 = tmp_fu_373_p3;

assign zext_ln91_2_fu_411_p1 = tmp_6_fu_395_p3;

assign zext_ln91_3_fu_469_p1 = ow_1_mid2_fu_265_p3;

assign zext_ln91_4_fu_473_p1 = ow_1_mid2_fu_265_p3;

assign zext_ln91_5_fu_483_p1 = add_ln91_1_fu_477_p2;

assign zext_ln91_fu_297_p1 = tmp_2_fu_289_p3;

assign zext_ln93_1_fu_459_p1 = tmp_8_fu_443_p3;

assign zext_ln93_2_fu_495_p1 = add_ln93_1_fu_489_p2;

assign zext_ln93_fu_429_p1 = tmp_1_fu_421_p3;

assign zext_ln95_1_fu_333_p1 = select_ln88_fu_273_p3;

assign zext_ln95_2_fu_363_p1 = tmp_4_fu_347_p3;

assign zext_ln95_3_fu_552_p1 = add_ln95_1_reg_657;

assign zext_ln95_fu_323_p1 = tmp_3_fu_315_p3;

endmodule //cnn_tinylenet_hls_cnn_tinylenet_hls_Pipeline_POOL1_OC_POOL1_OH_POOL1_OW
